apiVersion: apps/v1
kind: Deployment
metadata:
  name: simhoperator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: simhoperator
  template:
    metadata:
      labels:
        name: simhoperator
    spec:
      serviceAccountName: simhoperator
      containers:
        - name: simhoperator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          command:
          - simhoperator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "simhoperator"
