kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: simhoperator
subjects:
- kind: ServiceAccount
  name: simhoperator
roleRef:
  kind: Role
  name: simhoperator
  apiGroup: rbac.authorization.k8s.io
